name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy src to docs
        run: |
          rm -r docs
          mkdir docs
          cp -r dist/* docs/  # Adjust this line to match your build folder name

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push
